# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the source branch (change to your source branch)
  push:
    branches: ["main"] # Change to the branch that contains your source code

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10' # Use the version of Python you need for Sphinx

      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme

      - name: Build Sphinx documentation
        run: |
          cd docs # Change to your documentation directory if needed
          make clean
          make html

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_PAGES_TOKEN}}
          publish_dir: ./docs/_build/html # Change to the path of your built HTML files
